spring.application.name=event-booking

server.port=8084
#
## ===== DATABASE 1 (Primary) =====
#spring.datasource.url=jdbc:postgresql://localhost:5432/event-db
#spring.datasource.username=postgres
#spring.datasource.password=Dave
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#booking.expiry.scheduler.delay-ms=60000
#
#payment.webhook.url=http://localhost:8084/api/webhooks/payment
#payment.webhook.secret=dummy-webhook-secret
#payment.dummy.delay-ms=5000


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

booking.expiry.scheduler.delay-ms=${BOOKING_EXPIRY_SCHEDULER_DELAY_MS}

payment.webhook.url=${PAYMENT_WEBHOOK_URL}
payment.webhook.secret=${PAYMENT_WEBHOOK_SECRET}
payment.dummy.delay-ms=${PAYMENT_DUMMY_DELAY_MS}

